In [1]:
dataset = '/home/juma/data/net_intrusion/CIC-IDS-2018/CSVs/sf_sr_1000_l'
file_ending = '*Meter.csv'

In [2]:
%load_ext autoreload
from utils import read_data

In [3]:
data = read_data(dataset,file_ending)
data.shape

/home/juma/data/net_intrusion/CIC-IDS-2018/CSVs/sf_sr_1000_l/*Meter.csv
filenames  ['/home/juma/data/net_intrusion/CIC-IDS-2018/CSVs/sf_sr_1000_l/Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv', '/home/juma/data/net_intrusion/CIC-IDS-2018/CSVs/sf_sr_1000_l/Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv', '/home/juma/data/net_intrusion/CIC-IDS-2018/CSVs/sf_sr_1000_l/Tuesday-20-02-2018_TrafficForML_CICFlowMeter.csv', '/home/juma/data/net_intrusion/CIC-IDS-2018/CSVs/sf_sr_1000_l/Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv', '/home/juma/data/net_intrusion/CIC-IDS-2018/CSVs/sf_sr_1000_l/Friday-16-02-2018_TrafficForML_CICFlowMeter.csv', '/home/juma/data/net_intrusion/CIC-IDS-2018/CSVs/sf_sr_1000_l/Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv', '/home/juma/data/net_intrusion/CIC-IDS-2018/CSVs/sf_sr_1000_l/Friday-23-02-2018_TrafficForML_CICFlowMeter.csv', '/home/juma/data/net_intrusion/CIC-IDS-2018/CSVs/sf_sr_1000_l/Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv', '/home/juma/data/net_intrusion/CIC-IDS-2018/CSVs/sf_sr_1000_l/Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv']

(38160, 58)

In [4]:
data.head()

,Flowid,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Feduration,total_fpackets,total_bpackets,...,flow_fin,flow_syn,flow_rst,flow_psh,flow_ack,flow_urg,downUpRatio,Act_data_pkt_forward,min_seg_size_forward,Label
0,131.202.242.193-172.31.69.25-9984-22- 6,131.202.242.193,9984,172.31.69.25,22,6,2018-02-14 15:42:30,0,357.0,0.0,...,0,0,0,0,1,0,-1.0,0,20.0,Benign
1,13.58.98.64-172.31.69.25-34612-22- 6,13.58.98.64,34612,172.31.69.25,22,6,2018-02-14 15:32:30,0,714.0,0.0,...,0,0,0,0,1,0,-1.0,0,32.0,Benign
2,13.58.98.64-172.31.69.25-34452-22- 6,13.58.98.64,34452,172.31.69.25,22,6,2018-02-14 15:32:25,0,635.0,0.0,...,0,0,0,0,1,0,-1.0,0,32.0,Benign
3,13.58.98.64-172.31.69.25-34422-22- 6,13.58.98.64,34422,172.31.69.25,22,6,2018-02-14 15:32:24,0,519.0,0.0,...,0,0,0,1,1,0,0.0,519,32.0,Benign
4,172.31.69.25-13.58.98.64-22-34382- 6,172.31.69.25,22,13.58.98.64,34382,6,2018-02-14 15:32:23,0,1334.0,0.0,...,0,0,0,1,1,0,0.0,1334,32.0,Benign

In [7]:
from classifiers.shallows import LinearClassifier  
from sklearn.model_selection import train_test_split

In [8]:
data = data.sample(frac=1)
X = data.values[:,:-1]
y = data['Label'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.20, random_state=42)

In [9]:
regs = [1e-5,1e-4,1e-3]
learning_rates = [1e-4,1e-3,1e-2]
optim = 'Adam'
for reg in regs:
    for lr  in learning_rates: